# Generated by Django 4.1.7 on 2023-04-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_user_name_review_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='User_name',
            new_name='user_name',
        ),
    ]
